FROM python:3.12-slim

# Prevents Python buffering logs
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /{{cookiecutter.project_slug}}

# System dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies first ( better caching )
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy Project
COPY . .

# Make entrypoint executable
RUN chmod +x /{{cookiecutter.project_slug}}/entrypoint.sh

EXPOSE 8000
